sonar.projectKey=gastonDaRosa_portfolio-devops
sonar.organization=gastondarosa
sonar.sources=.
sonar.exclusions=**/*.md,**/.github/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
